name: wg-manage # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: "1.0" # just for humans, typically '1.2+git' or '1.3.2'
summary: A command-line tool to manage Wireguard configuration
description: |
  wg-manage allows to keep your wireguard configurations in-sync across
  clients and servers by keeping a single yaml configuration file that's
  then used to generate device-specific .conf files standard Wireguard
  tools (wg, wg-quick, device clients) understand. Requires wireguard
  tools to be installed on the computer running wg-manage.

grade: stable
confinement: strict

parts:
  wg-manage:
    plugin: go
    source: https://github.com/ofcoursedude/wg-manage.git
apps:
  wg-manage:
    command: bin/wg-manage
